services:
  server:
    image: bueti/shrinkster:${TAG}
    build:
      context: .
      target: final
    ports:
      - 443:8080
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy

  db:
   image: postgres:16.0-alpine3.18
   restart: always
   user: postgres
   volumes:
     - db-data:/var/lib/postgresql/data
   env_file:
     - .env
   expose:
     - 5432
   healthcheck:
     test: [ "CMD", "pg_isready" ]
     interval: 5s
     timeout: 3s
     retries: 5
volumes:
  db-data:
