services:
  server:
    image: bueti/shrinkster:${TAG}
    build:
      context: .
      target: final
    ports:
      - 8080:8080
    environment:
      DSN: ${DSN}
      SIGNING_KEY: ${SIGNING_KEY}
      TLS_CERT: ${TLS_CERT}
      TLS_KEY: ${TLS_KEY}
      TAG: ${TAG}
    depends_on:
      db:
        condition: service_healthy

  db:
   image: postgres:16.0-alpine3.18
   restart: always
   user: postgres
   secrets:
     - db-password
   volumes:
     - db-data:/var/lib/postgresql/data
   environment:
     - POSTGRES_DB=shrinkster
     - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
   expose:
     - 5432
   healthcheck:
     test: [ "CMD", "pg_isready" ]
     interval: 10s
     timeout: 5s
     retries: 5
   ports:
     - "5432:5432"
volumes:
  db-data:
secrets:
  db-password:
    file: password.txt
