name: Build and Test Go App

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**README.md'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        run: |
          npm install -D tailwindcss
          npx tailwindcss init

      - name: Build Tailwind CSS
        run: |
          npm run build

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Build Go App
        run: |
          go build -ldflags='-s -w' -o=./api ./cmd/api
