  on:
    push:
      branches:
        - main
  jobs:
    deploy:
      runs-on: ubuntu-latest
      steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set outputs
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Generate ioverlander.env
        uses: SpicyPizza/create-envfile@v2
        with:
          envkey_SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
          envkey_SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
          envkey_TLS_CERT: ${{ secrets.TLS_CERT }}
          envkey_TLS_KEY: ${{ secrets.TLS_KEY }}
          envkey_DSN: ${{ secrets.DSN }}
          envkey_SHA_SHORT: ${{ steps.vars.outputs.sha_short }}
          directory: .
          file_name: .env

      - name: Deploy to staging
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd shrinkster
            export TAG=$(grep SHA_SHORT .env | cut -d '=' -f2)
            docker-compose pull
            docker-compose up -d
